#ifndef CAPITALS_HPP
#define CAPITALS_HPP

#include <map>
#include <string>

struct CaseInsensitiveCompare { // case-insensitive comparison
    bool operator()(const std::string& a, const std::string& b) const {
        return std::lexicographical_compare(
            a.begin(), a.end(), 
            b.begin(), b.end(), 
            [](char c1, char c2) { return std::tolower(c1) < std::tolower(c2); }
        );
    }
};

const std::map<std::string, std::string, CaseInsensitiveCompare> capitals = {
    {"Afghanistan", "Kabul"},
    {"Albania", "Tirana"},
    {"Algeria", "Algeri"},
    {"Andorra", "Andorra la Vella"},
    {"Angola", "Luanda"},
    {"Antigua e Barbuda", "Saint John's"},
    {"Arabia Saudita", "Riad"},
    {"Argentina", "Buenos Aires"},
    {"Armenia", "Erevan"},
    {"Australia", "Canberra"},
    {"Austria", "Vienna"},
    {"Azerbaigian", "Baku"},
    {"Bahamas", "Nassau"},
    {"Bahrein", "Manama"},
    {"Bangladesh", "Dacca"},
    {"Barbados", "Bridgetown"},
    {"Belgio", "Bruxelles"},
    {"Belize", "Belmopan"},
    {"Benin", "Porto-Novo"},
    {"Bhutan", "Thimphu"},
    {"Bielorussia", "Minsk"},
    {"Birmania", "Naypyidaw"},
    {"Bolivia", "Sucre(de iure, giudiziaria)La Paz(de facto, legislativa ed amministrativa)"},
    {"Bosnia ed Erzegovina", "Sarajevo"},
    {"Botswana", "Gaborone"},
    {"Brasile", "Brasilia"},
    {"Brunei", "Bandar Seri Begawan"},
    {"Bulgaria", "Sofia"},
    {"Burkina Faso", "Ouagadougou"},
    {"Burundi", "Gitega"},
    {"Cambogia", "Phnom Penh"},
    {"Camerun", "Yaoundé"},
    {"Canada", "Ottawa"},
    {"Capo Verde", "Praia"},
    {"Rep. Ceca", "Praga"},
    {"Rep. Centrafricana", "Bangui"},
    {"Ciad", "N'Djamena"},
    {"Cile", "Santiago del Cile"},
    {"Cina", "Pechino"},
    {"Cipro", "Nicosia"},
    {"Colombia", "Bogotà"},
    {"Comore", "Moroni"},
    {"Rep. del Congo", "Brazzaville"},
    {"RD del Congo", "Kinshasa"},
    {"Corea del Nord", "Pyongyang"},
    {"Corea del Sud", "Seul"},
    {"Costa d'Avorio", "Yamoussoukro"},
    {"Costa Rica", "San José"},
    {"Croazia", "Zagabria"},
    {"Cuba", "L'Avana"},
    {"Danimarca", "Copenaghen"},
    {"Dominica", "Roseau"},
    {"Rep. Dominicana", "Santo Domingo"},
    {"Ecuador", "Quito"},
    {"Egitto", "Il Cairo"},
    {"El Salvador", "San Salvador"},
    {"Emirati Arabi Uniti", "Abu Dhabi"},
    {"Eritrea", "Asmara"},
    {"Estonia", "Tallinn"},
    {"Etiopia", "Addis Abeba"},
    {"Figi", "Suva"},
    {"Filippine", "Manila"},
    {"Finlandia", "Helsinki"},
    {"Francia", "Parigi"},
    {"Gabon", "Libreville"},
    {"Gambia", "Banjul"},
    {"Georgia", "Tbilisi"},
    {"Germania", "Berlino"},
    {"Ghana", "Accra"},
    {"Giamaica", "Kingston"},
    {"Giappone", "Tokyo"},
    {"Gibuti", "Gibuti"},
    {"Giordania", "Amman"},
    {"Grecia", "Atene"},
    {"Grenada", "Saint George's"},
    {"Guatemala", "Città del Guatemala"},
    {"Guinea", "Conakry"},
    {"Guinea-Bissau", "Bissau"},
    {"Guinea Equatoriale", "Malabo"},
    {"Guyana", "Georgetown"},
    {"Haiti", "Port-au-Prince"},
    {"Honduras", "Tegucigalpa"},
    {"India", "Nuova Delhi"},
    {"Indonesia", "Giacarta(de facto, capitale uscente)Nusantara(de iure, capitale in costruzione)"},
    {"Iran", "Teheran"},
    {"Iraq", "Baghdad"},
    {"Irlanda", "Dublino"},
    {"Islanda", "Reykjavík"},
    {"Isole Marshall", "Majuro(Delap-Uliga-Djarrit)"},
    {"Israele", "Gerusalemme(statusconteso)"},
    {"Italia", "Roma"},
    {"Kazakistan", "Astana"},
    {"Kenya", "Nairobi"},
    {"Kirghizistan", "Biškek"},
    {"Kiribati", "Tarawa Sud"},
    {"Kuwait", "Al Kuwait"},
    {"Laos", "Vientiane"},
    {"Lesotho", "Maseru"},
    {"Lettonia", "Riga"},
    {"Libano", "Beirut"},
    {"Liberia", "Monrovia"},
    {"Libia", "Tripoli"},
    {"Liechtenstein", "Vaduz"},
    {"Lituania", "Vilnius"},
    {"Lussemburgo", "Lussemburgo"},
    {"Macedonia del Nord", "Skopje"},
    {"Madagascar", "Antananarivo"},
    {"Malawi", "Lilongwe"},
    {"Malaysia", "Kuala Lumpur(de iure, costituzionale e legislativa)Putrajaya(de facto, amministrativa e giudiziaria)"},
    {"Maldive", "Malé"},
    {"Mali", "Bamako"},
    {"Malta", "La Valletta"},
    {"Marocco", "Rabat"},
    {"Mauritania", "Nouakchott"},
    {"Mauritius", "Port Louis"},
    {"Messico", "Città del Messico"},
    {"Micronesia", "Palikir"},
    {"Moldavia", "Chișinău"},
    {"Monaco", "Monaco"},
    {"Mongolia", "Ulan Bator"},
    {"Montenegro", "Podgorica"},
    {"Mozambico", "Maputo"},
    {"Namibia", "Windhoek"},
    {"Nauru", "Nessuna(de iure)Yaren(de facto)"},
    {"Nepal", "Katmandu"},
    {"Nicaragua", "Managua"},
    {"Niger", "Niamey"},
    {"Nigeria", "Abuja"},
    {"Norvegia", "Oslo"},
    {"Nuova Zelanda", "Wellington"},
    {"Oman", "Mascate"},
    {"Regno dei Paesi Bassi", "Amsterdam(de iure)L'Aia(de facto)"},
    {"Pakistan", "Islamabad"},
    {"Palau", "Ngerulmud"},
    {"Palestina", "Gerusalemme Est(de iure)Ramallah(de facto)"},
    {"Panama", "Panama"},
    {"Papua Nuova Guinea", "Port Moresby"},
    {"Paraguay", "Asunción"},
    {"Perù", "Lima"},
    {"Polonia", "Varsavia"},
    {"Portogallo", "Lisbona"},
    {"Qatar", "Doha"},
    {"Regno Unito", "Londra"},
    {"Romania", "Bucarest"},
    {"Ruanda", "Kigali"},
    {"Russia", "Mosca"},
    {"Saint Kitts e Nevis", "Basseterre"},
    {"Saint Vincent e Grenadine", "Kingstown"},
    {"Isole Salomone", "Honiara"},
    {"Samoa", "Apia"},
    {"San Marino", "Città di San Marino"},
    {"Saint Lucia", "Castries"},
    {"São Tomé e Príncipe", "São Tomé"},
    {"Senegal", "Dakar"},
    {"Serbia", "Belgrado"},
    {"Seychelles", "Victoria"},
    {"Sierra Leone", "Freetown"},
    {"Singapore", "Nessuna(città-stato)"},
    {"Siria", "Damasco"},
    {"Slovacchia", "Bratislava"},
    {"Slovenia", "Lubiana"},
    {"Somalia", "Mogadiscio"},
    {"Spagna", "Madrid"},
    {"Sri Lanka", "Sri Jayawardenapura Kotte"},
    {"Stati Uniti", "Washington"},
    {"Sudafrica", "Bloemfontein(giudiziaria)Città del Capo(legislativa)Pretoria(amministrativa)"},
    {"Sudan", "Khartum"},
    {"Sudan del Sud", "Giuba"},
    {"Suriname", "Paramaribo"},
    {"Svezia", "Stoccolma"},
    {"Svizzera", "Nessuna(de iure)Berna(de facto)"},
    {"eSwatini", "Lobamba(legislativa)Mbabane(amministrativa)"},
    {"Tagikistan", "Dušanbe"},
    {"Taiwan", "Nessuna(de iure)Taipei(de facto)"},
    {"Tanzania", "Dodoma"},
    {"Thailandia", "Bangkok"},
    {"Timor Est", "Dili"},
    {"Togo", "Lomé"},
    {"Tonga", "Nukuʻalofa"},
    {"Trinidad e Tobago", "Port of Spain"},
    {"Tunisia", "Tunisi"},
    {"Turchia", "Ankara"},
    {"Turkmenistan", "Aşgabat"},
    {"Tuvalu", "Funafuti"},
    {"Ucraina", "Kiev"},
    {"Uganda", "Kampala"},
    {"Ungheria", "Budapest"},
    {"Uruguay", "Montevideo"},
    {"Uzbekistan", "Tashkent"},
    {"Vanuatu", "Port Vila"},
    {"Città del Vaticano", "Nessuna(città-stato)"},
    {"Venezuela", "Caracas"},
    {"Vietnam", "Hanoi"},
    {"Yemen", "Sana'a"},
    {"Zambia", "Lusaka"},
    {"Zimbabwe", "Harare"},
};

#endif // CAPITALS_HPP
